/**
 * @file gasket.h
 * 
 * @author Sam Foucart sf241616@ohio.edu
 * 
 * @brief A modified version of Angel, Shreiner, Chelberg's sierpinski gasket program.
 * The modification changes the color and implements panning and zooming.
 * 
 */
#ifndef __GASKET_H__
#define __GASKET_H__


/**
 * generate_points uses the sierpinski gasket algorithm to generate a dynamic array of points
 * that is then stored in a global variable called points.
 * 
 * @param npoints the number of points to be generated by the algorithm
 * 
 * @note the global variable points must be deleted to avoid a memory leak
 */
void generate_points (int npoints);

/**
 * init Initializes the shaders and calls generate_points to initialize the program
 */
void init();
extern "C" void display();
extern "C" void keyboard(unsigned char key, int x, int y);
extern "C" void mouse(int button, int state, int x, int y);

#endif